#!/bin/sh

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CALLSIGN_DIR="$1"
[ -n "$CALLSIGN_DIR" ] || CALLSIGN_DIR="callsigns"

$CWD/live-dj
LIVE=$?
LIVE=1

if [ $LIVE -ne 0 ]; then
    $CWD/stream-stop
    $CWD/play-callsign "$CALLSIGN_DIR"
    $CWD/stream-start
fi
