#!/usr/bin/env python3

import sys
import os
import random

def list_files(*names):
    files = []
    for name in names:
        if os.path.isdir(name):
            for item in os.listdir(name):
                files = files + list_files(f'{name}/{item}')
        elif os.path.isfile(name) and not os.path.islink(name):
            files.append(name)
    return files

files = list_files(*sys.argv[1:])
print(random.choice(files))
