#!/bin/sh

CALLSIGN_DIR="$1"
[ -n "$CALLSIGN_DIR" ] || CALLSIGN_DIR="callsigns"

stream-status > /dev/null && stream-stop

CALLSIGN_FILE="$(choose-random-file $CALLSIGN_DIR)"
tmux new-session -s callsign "ffplay -autoexit $CALLSIGN_FILE"
