#!/bin/sh

CALLSIGN_DIR="$1"
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
[ -n "$CALLSIGN_DIR" ] || CALLSIGN_DIR="callsigns"

$CSW/stream-status && $CSW/stream-stop

CALLSIGN_FILE="$($CSW/choose_random_file $CALLSIGN_DIR)"
tmux new-session -s callsign "ffplay -autoexit $CALLSIGN_FILE"
