#!/bin/sh

STREAM_URL="https://krlxfm.out.airtime.pro/krlxfm_a"
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

$CWD/stream-status
STATUS=$?

if [ $STATUS -eq 0 ]; then
    read -p "Attach to existing session? [y/N] " ATTACH
    if [ "$ATTACH" = "y" || "$ATTACH" = "Y" ]; then
        tmux attach-session -t stream_live
    fi
    exit 0
fi

tmux new-session -s stream_live "ffplay $STREAM_URL"
