#!/bin/sh

STREAM_URL="https://krlxfm.out.airtime.pro/krlxfm_a"

stream-status > /dev/null && echo "Stream is already listening live." && exit 1

tmux new-session -ds stream_live "ffplay $STREAM_URL"
